#!/bin/sh

if ! type commitlint >/dev/null 2>/dev/null; then
	echo ""
    echo "commitlint could not be found"
    echo "try again after installing commitlint or add commitlint to PATH"
	echo ""
    exit 2;
fi

if ( grep -q "Merge branch" $1 ); then
    exit 0;
fi

commitlint lint --message $1

