# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}
      {{- if ne .Arch "all" }}_{{ .Arch }}{{ end }}

release:
  github:
